*** Variable ***
${address_locator.continue}                     id=continue
${address_locator.cancel}                       id=cancel
${address_locator.first_name}                   id=first-name
${address_locator.last_name}                    id=last-name
${address_locator.zipcode}                      id=postal-code
${address_locator.header}                       xpath=//div[@class="header_secondary_container"]/span[contains(text(),"Checkout: Your Information")]
