*** Settings ***
Resource        ${CURDIR}/../locator/login_locator.resource
Resource        ${CURDIR}/../locator/product_locator.resource
Resource        ${CURDIR}/../locator/address_locator.resource
Resource        ${CURDIR}/../locator/cart_locator.resource
Resource        ${CURDIR}/../locator/payment_locator.resource
Resource        ${CURDIR}/../locator/finish_locator.resource

Resource        ${CURDIR}/../component/locator/burger_locator.resource
Resource        ${CURDIR}/../component/locator/cart_locator.resource