*** keyword ***
click open burger menu
    common_function.click by element        ${burger_locator.menu_botton}

click all item tap
    common_function.click by element        ${burger_locator.all_item_tap}

click about tap
    common_function.click by element        ${burger_locator.about_tap}

click logout
    common_function.click by element        ${burger_locator.logout_tap}

click reset app state
    common_function.click by element        ${burger_locator.reset_tap}
